name: Sync Files to Server

on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" >> ./id_rsa
          chmod 600 id_rsa

      - name: Deploy with rsync
        run: scp -C -o StrictHostKeyChecking=no -i ./id_rsa ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/laravel-octane-roadrunner
