name: Sync Files to Server

on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "23.88.54.223 ecdsa-sha2-nistp256 YourServerSSHHostKey" >> ~/.ssh/known_hosts
        env:
          SERVER_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Sync files with rsync
        run: |
          rsync -avz --delete ./ root@23.88.54.223:/root/laravel-octane-roadrunner
